logging:
  level:
    org:
      pokemon: "DEBUG"

cardsSize: 4

pokemon:
  api:
    url: "https://api.pokemontcg.io/v2/cards?select=id,name,hp,types,attacks&page=1&pageSize=50"

spring:
  config:
    import: db.properties
  datasource:
    driverClassName: org.postgresql.Driver
