name: Pokemon battle simulator CI/CD development pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
